### ISSUE TITLE
SoundManager

### ISSUE THREAD

**Issue by Porto1090** [BassedWarrior/TC2005B.501_E1#114]
# Add Music To the Game

## Related Requirements

- #[issue_number]

## Goal in Context

(*write here*)

## Preconditions

(*write here*)

## Successful End Condition

(*write here*)

## Failed End Condition

(*write here*)

## Primary Actors

(*write here*)

## Secondary Actors

- Unity

## Trigger

(*write here*)

## Main Flow

1. (*write here*)

## Use Case Diagram
![Use Case Diagram](./SoftwareEngineering/Images/use_case_diagram.png)

**Comment by BassedWarrior** [comment]
Solved with #120
